version: "3"
services:

#  frontend:
#    build:
#      context: ./
#      dockerfile: ./docker/config/frontend/Dockerfile
#    depends_on:
#      - nodejs
#    volumes:
#      - ./node-react/frontend:/usr/src/app/
#      - ./docker/config/frontend/init.sh:/init.sh
#    ports:
#      - "80:3000"
#    networks:
#      - internal
#
#  nodejs:
#    build:
#      context: ./
#      dockerfile: ./docker/config/nodejs/Dockerfile
#    depends_on:
#      - symfony
#    ports:
#      - "3001:3001"
#    environment:
#      SYMFONY_HOST: http://symfony/
#    volumes:
#      - ./node-react/nodejs:/usr/src/app/
#      - ./docker/config/nodejs/init.sh:/init.sh
#    networks:
#      - internal

  database:
    build:
      context: ./
      dockerfile: ./docker/config/database/Dockerfile
    volumes:
      - ./docker/data/database:/var/lib/mysql
      - ./docker/logs/database:/var/log/mysql
    ports:
      - '3306:3306'
    networks:
      - internal

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      MAX_EXECUTION_TIME: 3600
      UPLOAD_LIMIT: 500M
    volumes:
      - ./docker/data/phpmyadmin/sessions:/sessions
    ports:
      - '8080:80'
    networks:
      - internal

networks:
  internal:
    driver: bridge