version: "3"
services:

  database:
    build:
      context: ./
      dockerfile: ./docker/config/database/Dockerfile
    volumes:
      - ./docker/data/database:/var/lib/mysql
      - ./docker/logs/database:/var/log/mysql
    ports:
      - '3306:3306'
    networks:
      - internal

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      MAX_EXECUTION_TIME: 3600
      UPLOAD_LIMIT: 500M
    volumes:
      - ./docker/data/phpmyadmin/sessions:/sessions
    ports:
      - '8080:80'
    networks:
      - internal

networks:
  internal:
    driver: bridge